---
title: 2020-03-22-parametric-tests
author: ~
date: '2020-03-22'
slug: parametric-tests
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-03-22T07:45:24+10:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
bibliography: library.bib
citation_package: biblatex
csl: ieee-with-url.csl
---
In both statistic and to some extend maths, the concept of linearity and its counter term non-linearity is particularly important first step in knowing your data.  It will define the parametric or non parametric tools you can use on the dataset and considering there are at least 75 tools that make up parametric testing, understanding the form of your data is a crucial first step in analysis [@sheskin_handbook_1997]. An example of these tools is the least squared method which only works best on data that are linear. 


would come under the branch of hypothetical testing where the analyst can find whether the predicted slop is between 95% confidence internal between an independent and dependent variabled $(x, y)$ hypothetical testing for research writing,  In areas like engineering and computer science, knowing what form your data is in will influence the algoritms you use.  For instance, in Singular Value Decomposition equation assumes linearity, 



## References


